### ISSUE TITLE
Failed to read Class-Path attribute from manifest of jar  json-lib-2.4-jdk15.ja

### ISSUE THREAD

**Issue by bigbugor** [linlinjava/litemall#127]
Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
	at java.base/java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:1002)
	at java.base/java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:1012)
	at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:467)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/java.io.InputStream.readNBytes(InputStream.java:490)
	at java.base/java.util.jar.JarFile.getBytes(JarFile.java:805)
	at java.base/java.util.jar.JarFile.getManifestFromReference(JarFile.java:419)
	at java.base/java.util.jar.JarFile.getManifest(JarFile.java:406)
	at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromManifestClassPathAttribute(ChangeableUrls.java:153)
	at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromClassPathOfJarManifestIfPossible(ChangeableUrls.java:129)
	... 17 more

**Comment by bigbugor** [comment]
jar包文件损坏，问题已解决
