### ISSUE TITLE
启动后台管理前端

### ISSUE THREAD

**Issue by lawrencewu** [linlinjava/litemall#132]
按照步骤在执行
npm install -g cnpm --registry=https://registry.npm.taobao.org
cd litemall/litemall-admin
cnpm install
在执行命令  cnpm run dev, 出现以下错误.

使用的是MACOS, 请大佬看看这个问题

[lawrence:litemall-admin lawrence$ cnpm run dev

> litemall-admin@0.1.0 dev /Users/lawrence/workspace/litemall/litemall-admin
> cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module 'brace-expansion'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/lawrence/workspace/litemall/litemall-admin/node_modules/_minimatch@3.0.4@minimatch/minimatch.js:10:14)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! litemall-admin@0.1.0 dev: `cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the litemall-admin@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lawrence/.npm/_logs/2019-02-28T08_24_52_527Z-debug.log

**Comment by iason2010** [comment]
大佬你好，我在centos上运行也遇到这问题了，请问有解决方法吗
