### ISSUE TITLE
退款证书 配置不生效，在路径在doccker 容器内确实存在 证书文件【/home/cpic/project/malltest/cert/apiclientl_cert.p12】不存在，请核实

### ISSUE THREAD

**Issue by down-to-earth1994** [linlinjava/litemall#432]
Caused by: com.github.binarywang.wxpay.exception.WxPayException: 证书文件【/home/cpic/project/malltest/cert/apiclientl_cert.p12】不存在，请核实！
        at com.github.binarywang.wxpay.config.WxPayConfig.initSSLContext(WxPayConfig.java:138)
        at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.initSSLContext(WxPayServiceApacheHttpImpl.java:129)
        at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.createHttpClientBuilder(WxPayServiceApacheHttpImpl.java:99)
        at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.post(WxPayServiceApacheHttpImpl.java:63)
        ... 114 common frames omitted

**Comment by down-to-earth1994** [comment]
配置在docker 容器/opt/ 目录下生效了
