### ISSUE TITLE
mvn spring-boot:run报错

### ISSUE THREAD

**Issue by yutungnet** [linlinjava/litemall#93]
数据库监听了 内网IP+端口，
使用litemall-db里面的sql，创建了@localhost的用户，报错：
2018-11-27 09:57:14.510 ERROR 1892 --- [  restartedMain] com.alibaba.druid.pool.DruidDataSource   : init datasource error, url: jdbc:mysql://localhost:3306/litemall?useUnicode=true&cha
racterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false

com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_161]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_161]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_161]

修改sql，把localhost改为 mysql监听的ip，问题解决了。

**Comment by linlinjava** [comment]
所以，问题解决了，我这里不需要修改什么地方吧。
